# Generated by Django 4.2 on 2024-02-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_discount_product_new_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Скидка в %'),
        ),
    ]
