# Generated by Django 4.2 on 2024-03-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantyty',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
