# Generated by Django 5.1.1 on 2024-10-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_quantyty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержимое письма'),
        ),
    ]
