# Generated by Django 4.2 on 2024-02-24 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCode',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.order')),
                ('post_code', models.CharField(blank=True, max_length=100, verbose_name='Код почты')),
                ('order_code', models.CharField(blank=True, max_length=10, verbose_name='Ключ')),
                ('status', models.CharField(blank=True, choices=[('1', 'Заказ принят'), ('2', 'Заказ отправлен по почте'), ('3', 'Заказ прибыл'), ('4', 'Заказ взят клиентом')], max_length=50, verbose_name='Статус посылки')),
            ],
            options={
                'verbose_name': 'Почтовый код',
                'verbose_name_plural': 'Почтовые коды',
            },
        ),
        migrations.CreateModel(
            name='TextArea',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='orders.order')),
                ('text', models.CharField(blank=True, max_length=700)),
            ],
            options={
                'verbose_name': 'Дополнение к заказу',
            },
        ),
    ]
