# Generated by Django 4.2 on 2024-03-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_postcode_textarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcode',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Заказ принят'), ('2', 'Заказ отправлен по почте'), ('3', 'Заказ прибыл'), ('4', 'Заказ взят клиентом')], default='1', max_length=50, verbose_name='Статус посылки'),
        ),
    ]
