# Generated by Django 5.1.1 on 2024-10-05 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_postcode_status'),
        ('shop', '0006_alter_feedback_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default='Продукт удален', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='order_items', to='shop.product'),
        ),
    ]
