# Generated by Django 5.1.1 on 2025-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='text',
            field=models.CharField(blank=True, max_length=700, verbose_name='Дополнение к заказу'),
        ),
        migrations.DeleteModel(
            name='TextArea',
        ),
    ]
