# Generated by Django 5.1.1 on 2025-03-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderitem_options_postcode_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcode',
            name='user',
        ),
    ]
