# Generated by Django 5.1.1 on 2025-03-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_postcode_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
