# Generated by Django 5.1.1 on 2025-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='Скидка в %'),
        ),
    ]
